print("Welcome to the tip calculator.")
total_bill = float( input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
pay = round( total_bill * (1 + round(tip/100, 2)) / people, 2)
print(f"Each person should pay: ${pay:.2f}")
